encode_vi={u"a".encode('utf-8'):"a",
u"ă".encode('utf-8'):"aw",
u"â".encode('utf-8'):"aa",
u"u".encode('utf-8'):"u",
u"ư".encode('utf-8'):"uw",
u"o".encode('utf-8'):"o",
u"ơ".encode('utf-8'):"ow",
u"i".encode('utf-8'):"i",
u"e".encode('utf-8'):"e",
u"ê".encode('utf-8'):"ee",
u"à".encode('utf-8'):"af",
u"ằ".encode('utf-8'):"awf",
u"ầ".encode('utf-8'):"aaf",
u"ù".encode('utf-8'):"uf",
u"ừ".encode('utf-8'):"uwf",
u"ò".encode('utf-8'):"of",
u"ờ".encode('utf-8'):"owf",
u"ì".encode('utf-8'):"if",
u"è".encode('utf-8'):"ef",
u"ề".encode('utf-8'):"eef",
u"ả".encode('utf-8'):"ar",
u"ẳ".encode('utf-8'):"awr",
u"ẩ".encode('utf-8'):"aar",
u"ủ".encode('utf-8'):"ur",
u"ử".encode('utf-8'):"uwr",
u"ỏ".encode('utf-8'):"or",
u"ở".encode('utf-8'):"owr",
u"ỉ".encode('utf-8'):"ir",
u"ẻ".encode('utf-8'):"er",
u"ể".encode('utf-8'):"eer",
u"á".encode('utf-8'):"as",
u"ắ".encode('utf-8'):"aws",
u"ấ".encode('utf-8'):"aas",
u"ú".encode('utf-8'):"us",
u"ứ".encode('utf-8'):"uws",
u"ó".encode('utf-8'):"os",
u"ớ".encode('utf-8'):"ows",
u"í".encode('utf-8'):"is",
u"é".encode('utf-8'):"es",
u"ế".encode('utf-8'):"ees",
u"ạ".encode('utf-8'):"aj",
u"ặ".encode('utf-8'):"awj",
u"ậ".encode('utf-8'):"aaj",
u"ụ".encode('utf-8'):"uj",
u"ự".encode('utf-8'):"uwj",
u"ọ".encode('utf-8'):"oj",
u"ợ".encode('utf-8'):"owj",
u"ị".encode('utf-8'):"ij",
u"ẹ".encode('utf-8'):"ej",
u"ệ".encode('utf-8'):"eej",
u"ô".encode('utf-8'):"oox",
u"ố".encode('utf-8'):"oos",
u"ổ".encode('utf-8'):"oof",
u"ộ".encode('utf-8'):"ooj",
u"ồ".encode('utf-8'):"oof",
u"ỗ".encode('utf-8'):"oox",
u"ã".encode('utf-8'):"ax",
u"ẵ".encode('utf-8'):"awx",
u"ẫ".encode('utf-8'):"aax",
u"ũ".encode('utf-8'):"ux",
u"ữ".encode('utf-8'):"uwx",
u"õ".encode('utf-8'):"ox",
u"ỡ".encode('utf-8'):"owx",
u"ĩ".encode('utf-8'):"ix",
u"ẽ".encode('utf-8'):"ex",
u"ễ".encode('utf-8'):"eex",
u"đ".encode('utf-8'):"dd"

}

{u'a': 'a',
 u'e': 'e',
 u'i': 'i',
 u'o': 'o',
 u'u': 'u',
 u'\xe0': 'af',
 u'\xe1': 'as',
 u'\xe2': 'aa',
 u'\xe3': 'ax',
 u'\xe8': 'ef',
 u'\xe9': 'es',
 u'\xea': 'ee',
 u'\xec': 'if',
 u'\xed': 'is',
 u'\xf2': 'of',
 u'\xf3': 'os',
 u'\xf4': 'oo',
 u'\xf5': 'ox',
 u'\xf9': 'uf',
 u'\xfa': 'us',
 u'\xfd': 'ys',
 u'\u0103': 'aw',
 u'\u0111': 'dd',
 u'\u0129': 'ix',
 u'\u0169': 'ux',
 u'\u01a1': 'ow',
 u'\u01b0': 'uw',
 u'\u1ea1': 'aj',
 u'\u1ea3': 'ar',
 u'\u1ea5': 'aas',
 u'\u1ea7': 'aaf',
 u'\u1ea9': 'aar',
 u'\u1eab': 'aax',
 u'\u1ead': 'aaj',
 u'\u1eaf': 'aws',
 u'\u1eb1': 'awf',
 u'\u1eb3': 'awr',
 u'\u1eb5': 'awx',
 u'\u1eb7': 'awj',
 u'\u1eb9': 'ej',
 u'\u1ebb': 'er',
 u'\u1ebd': 'ex',
 u'\u1ebf': 'ees',
 u'\u1ec1': 'eef',
 u'\u1ec3': 'eer',
 u'\u1ec5': 'eex',
 u'\u1ec7': 'eej',
 u'\u1ec9': 'ir',
 u'\u1ecb': 'ij',
 u'\u1ecd': 'oj',
 u'\u1ecf': 'or',
 u'\u1ed1': 'oos',
 u'\u1ed3': 'oof',
 u'\u1ed5': 'oof',
 u'\u1ed7': 'oox',
 u'\u1ed9': 'ooj',
 u'\u1edb': 'ows',
 u'\u1edd': 'owf',
 u'\u1edf': 'owr',
 u'\u1ee1': 'owx',
 u'\u1ee3': 'owj',
 u'\u1ee5': 'uj',
 u'\u1ee7': 'ur',
 u'\u1ee9': 'uws',
 u'\u1eeb': 'uwf',
 u'\u1eed': 'uwr',
 u'\u1eef': 'uwx',
 u'\u1ef1': 'uwj',
 u'\u1ef3': 'yf',
 u'\u1ef7': 'yr',
 u'\u1ef9': 'yx'}



def replace_all(text, dic):
    for i, j in dic.iteritems():
        text = text.replace(i, j)
    return text
    
    M14U5mxcZx2u4s
